-- Import ACC Thai potential leads from Potential Lead for ACC_26Feb.csv
-- Generated: 2026-02-26 21:35:00
-- Type: LEAD2026FEB_THAIACC

-- Total: 17 leads

INSERT INTO leads (
    id, company_name, industry, country, city, website,
    key_person_name, key_person_title, key_person_email, key_person_phone,
    total_events, vietnam_events, number_of_delegates, notes, status, type, research_notes,
    created_at, updated_at
) VALUES
    ('acc-thai-asiapacific-symposium-on-elect-2026', 'Asia‑Pacific Symposium on Electromagnetic Compatibility (APEMC)', 'Physics / Electromagnetics', 'Vietnam', 'Da Nang', 'http://www.ewh.ieee.org/ieee/apo/', 'Ms Ewell Tan', NULL, 'ewell.tan@ieee.org', '+65 6778 2873', 0, 0, 700, 'VN Host: IEEE Vietnam Section; University of Danang. Contact: 0236 3822 041. Cycle: Annual • May. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-asiapacific-interventional-onc-2026', 'Asia‑Pacific Interventional Oncology Conference (APCIO)', 'Medical / Oncology', 'Vietnam', 'Da Nang', NULL, 'Dr Alex Tang', NULL, 'secretariat@mysir.org', NULL, 0, 0, 1000, 'VN Host: Vietnam Society of Interventional Radiology (VSIR); Vinmec. Contact: 0236 3711 111, info.dng@vinmec.com. Cycle: Biennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-annual-meeting-of-the-asian-or-2026', 'Annual Meeting of the Asian Organization for Crohn’s & Colitis (AOCC)', 'Medical / Gastroenterology', 'Vietnam', 'Da Nang', 'https://aocc-ibd.org', 'Dr Tan Soek Siam', NULL, 'tanss@selayanghospital.gov.my', NULL, 0, 0, 900, 'VN Host: Vietnam Association of Gastroenterology; Bach Mai Hospital. Contact: 0969 851 616. Department: Social work department. Cycle: Annual • June. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-society-of-wood-science-techno-2026', 'Society of Wood Science & Technology (SWST) Convention', 'Forest products', 'Vietnam', 'Da Nang', 'http://www.swst.org', 'Mrs Vicki L. Herian', NULL, 'vicki@swst.org', '+1 608 577 1342', 0, 0, 280, 'VN Host: VIFORES; Vietnam National University of Forestry. Contact: DH Ngong Lam 024 3384 0233, unable to contact. Cycle: Annual. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-aapa-aviation-emergency-respon-2026', 'AAPA Aviation Emergency Response Conference', 'Aviation / Safety', 'Vietnam', 'Da Nang', 'http://www.aapairlines.org', 'AAPA Secretariat', NULL, 'info@aapa.org.my', '+60 3 2162 1888', 0, 0, 134, 'VN Host: Vietnam Airlines; Civil Aviation Authority of Vietnam Vietnam Airlines;. Cycle: Biennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-asiapacific-council-of-optomet-2026', 'Asia‑Pacific Council of Optometry (APCO)', 'Medical / Optometry', 'Vietnam', 'Da Nang', 'http://www.asiapacificoptometry.org', 'APCO Secretariat', NULL, 'secretariat@asiapacificoptometry.org', '+61 7 3138 5738', 0, 0, 500, 'VN Host: Vietnam Optometry Association; Hanoi Medical University. Contact: 024 3852 3798. Cycle: Biennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: Unknown', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-international-association-of-g-2026', 'International Association of Gerontology & Geriatrics (IAGG Asia)', 'Healthy ageing', 'Vietnam', 'Da Nang', 'https://www.iagg.net', 'IAGG Secretariat', NULL, 'MSPH-IAGG@cumc.columbia.edu', NULL, 0, 0, 1000, 'VN Host: Vietnam Geriatrics Association; National Geriatric Hospital. Contact: Ban Thư Ký: HỘI NGHỊ LÃO KHOA,Bệnh viện Lão khoa Trung ương,. Cycle: Quadrennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: TBC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-christian-conference-of-asia-c-2026', 'Christian Conference of Asia (CCA) Assembly', 'Religious / Social', 'Vietnam', 'Da Nang', 'http://www.cca.org.hk', 'CCA Secretariat', NULL, 'cca@cca.org.hk', NULL, 0, 0, 800, 'VN Host: Vietnam Evangelical Alliance; Faith‑based NGOs. Contact: Liên hiệp Cộng đồng Tin Lành Việt Nam. Cycle: 4‑yearly. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-asian-society-of-transplantati-2026', 'Asian Society of Transplantation (AST) Congress', 'Medical / Transplant', 'Vietnam', 'Da Nang', 'http://www.txasia.org', 'AST Secretariat', NULL, 'info@siut.org', NULL, 0, 0, 1000, 'VN Host: Vietnam Transplant Association; Viet Duc Hospital. Contact: (024)38.253.531 Fax: (844) 8.248.308 benhvienvietduc.info@gmail.com. Cycle: Biennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-asiaoceania-thyroid-associatio-2026', 'Asia‑Oceania Thyroid Association (AOTA) Congress', 'Medical / Endocrinology', 'Vietnam', 'Da Nang', NULL, 'AOTA Secretariat', NULL, 'aota_office@aota.org', NULL, 0, 0, 800, 'VN Host: Vietnam Endocrinology Society ; National Hospital of Endocrinology. Contact: (Hội Nội tiết Việt Nam) Bệnh viện Nội tiết Trung ương 0903 597 695- 0905 155 617 ntdtdvn@gmail.com Khoa Nội Tổng hợp- Lão khoa, Bệnh viện Trung ương Huế, 16 Lê Lợi, phường Thuận Hóa, thành phố Huế. Cycle: Biennial. Next action: No information about this organization', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: Unknown', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-federation-of-asiapacific-reta-2026', 'Federation of Asia‑Pacific Retailers Association (FAPRA) Congress', 'Retail trade', 'Vietnam', 'Da Nang', 'http://www.fapra.net', 'FAPRA Secretariat', NULL, 'cgcc_intl@aliyun.com', NULL, 0, 0, 1000, 'VN Host: Vietnam Retailers Association; Saigon Co.op. Contact: Hiệp hội các nhà bán lẻ Việt Nam; Saigon Co.op. Cycle: Annual. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: Revenue share likely', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-international-water-associatio-2026', 'International Water Association (IWA) Asia‑Pacific Regional Conference', 'Water & sanitation', 'Vietnam', 'Da Nang', 'https://www.iwa-network.org', 'Mr Ganesh Pangare', NULL, 'ganesh.pangare@iwahq.org', NULL, 0, 0, 800, 'VN Host: Vietnam Water Supply & Sewerage Association; Danang Water Co.. Contact: Hội Cấp thoát nước Việt Nam; Công ty Cấp nước Đà Nẵng 024 3974 3457. Cycle: Biennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: Unknown', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-world-wide-web-conference-iw3c-2026', 'World Wide Web Conference (IW3C2)', 'ICT / Internet', 'Vietnam', 'Da Nang', NULL, 'IW3C2 Secretariat', NULL, 'info@iw3c2.org', NULL, 0, 0, 1200, 'VN Host: Vietnam Internet Association; Posts & Telecom Institute. Contact: Hiệp hội Internet Việt Nam; Viện Bưu chính Viễn thông 024 3633 0355. Cycle: Annual • April. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: Hosting fee / royalty', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-international-vegetarian-union-2026', 'International Vegetarian Union (IVU) World Congress', 'Lifestyle / Food', 'Vietnam', 'Da Nang', 'https://www.ivu.org', 'IVU Secretariat', NULL, 'info@ivu.org', NULL, 0, 0, 600, 'VN Host: Vietnam Vegetarian Society; Trúc Lâm Monastery Network. Contact: Hội Ăn Chay Việt Nam; Mạng lưới Thiền Viện Trúc Lâm. Department: PRESS CONFERENCE -  on October 20 at Hoang Yen Buffet Restaurant EVENT: VEGETARIAN FOOD FESTIVAL 2025 Time: October 31 - November 4, 2025 Location: Binh Phu Park - 10-12 Binh Phu Street, Binh Phu Ward, HCMC FREE ENTRY. Cycle: Triennial. Next action: continuing find out contact of organization in vietnam', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: None stated', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-international-fertilizer-assoc-2026', 'International Fertilizer Association (IFA) Global Conference', 'Agriculture', 'Vietnam', 'Da Nang', 'https://www.fertilizer.org', 'IFA Secretariat', NULL, 'info@fertilizer.org', NULL, 0, 0, 900, 'VN Host: Vietnam Fertilizer Association; PVFCCo. Contact: Hiệp hội Phân bón Việt Nam; PVFCCo  0393 963598. Cycle: Annual. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: Licence fee', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-international-council-for-open-2026', 'International Council for Open & Distance Education (ICDE) World Conference', 'Higher‑ed Tech', 'Vietnam', 'Da Nang', 'https://www.icde.org', 'ICDE Secretariat', NULL, 'icde@icde.org', NULL, 0, 0, 1200, 'VN Host: Hanoi Open University; Ministry of Education & Training. Contact: Viện Đại học Mở Hà Nội; Bộ Giáo dục và Đào tạo 024 3868 2321. Cycle: Biennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: Licence / revenue share', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('acc-thai-international-menopause-societ-2026', 'International Menopause Society (IMS) Congress', 'Women’s Health', 'Vietnam', 'Da Nang', 'https://www.imsociety.org', 'IMS Office', NULL, 'ims.society@imsociety.org', NULL, 0, 0, 1200, 'VN Host: Vietnam Menopause Society; National Obstetrics & Gynecology Hospital. Contact: Hội Mãn kinh Việt Nam; Bệnh viện Phụ sản Trung ương 1900 1029. Cycle: Biennial. Next action: Sent proposal about Ariyana and MICE presentation.', 'New', 'LEAD2026FEB_THAIACC', 'Royalty: TBC', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);