-- Import script for CORP and DMC leads from CSV files (2026)
-- Generated: 2026-02-13 17:20:57
-- Usage: Run this script after running migrations 003 and 004

-- Found 12 CORP leads
-- Found 15 DMC leads

INSERT INTO leads (
    id, company_name, industry, country, city, website,
    key_person_name, key_person_title, key_person_email, key_person_phone,
    total_events, vietnam_events, notes, status, type, research_notes,
    created_at, updated_at
) VALUES
    ('corp-dbs-si-2026', 'DBS', 'Banking / Financial Services', 'Singapore', 'Da Nang', NULL, 'TBD', 'Head of Events; APAC Travel Manager; Procurement (Travel & Meetings); HR Rewards & Recognition; Sales Enablement', NULL, NULL, 0, 0, 'Why target: Regional sales meetings, dealer incentives, leadership offsites. Vietnam signal: Likely SEA footprint. Partner angle: Pitch a premium but efficient offsite: ACC for plenary/breakouts + gala; combine with beach resort accommodation; emphasize short-haul and high perceived value. Offer ''one contract'' simplicity and preferred group pricing.. Suggested route: Via DMC (BCD/CTM/FCM) + direct warm intro', 'New', 'CORP', 'DBS incentive trip Vietnam; DBS regional meeting Da Nang; DBS offsite Vietnam; site:linkedin.com DBS Vietnam incentive', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-uob-si-2026', 'UOB', 'Banking / Financial Services', 'Singapore', 'Da Nang', NULL, 'TBD', 'Regional Events Lead; Marketing Events; Travel Manager; Procurement', NULL, NULL, 0, 0, 'Why target: Annual kickoffs and client events. Vietnam signal: Likely SEA footprint. Partner angle: Position Da Nang as alternative to Bangkok/Bali with fresh destination appeal. ACC provides scalable plenary + production readiness.. Suggested route: Via DMC + direct', 'New', 'CORP', 'UOB sales conference Vietnam; UOB incentive Hoi An; UOB meeting Da Nang', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-ocbc-si-2026', 'OCBC', 'Banking / Financial Services', 'Singapore', 'Da Nang', NULL, 'TBD', 'Regional Events; HR Rewards; Procurement Travel', NULL, NULL, 0, 0, 'Why target: Incentives + internal conferences. Vietnam signal: Likely SEA footprint. Partner angle: Offer budget tiers (good/better/best) and highlight quick airport-to-venue transfer and easy logistics.. Suggested route: Via DMC + direct', 'New', 'CORP', 'OCBC incentive trip Vietnam; OCBC regional offsite Da Nang; OCBC Hoi An gala', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-maybank-ma-2026', 'Maybank', 'Banking', 'Malaysia', 'Da Nang', NULL, 'TBD', 'Group HR; Rewards & Recognition; Travel Manager; Procurement', NULL, NULL, 0, 0, 'Why target: Large employee base; leadership and sales conferences. Vietnam signal: Likely regional/offshore travel. Partner angle: Offer cost-effective scale: ACC plenary + breakout + gala; propose 3 package tiers and ‘all-in’ per-delegate budgeting.. Suggested route: Via Mayflower / Apple MICE / Holiday Tours', 'New', 'CORP', 'Maybank incentive Vietnam; Maybank sales conference Vietnam; Maybank Da Nang meeting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-cimb-ma-2026', 'CIMB', 'Banking', 'Malaysia', 'Da Nang', NULL, 'TBD', 'Regional Events; HR Rewards; Procurement Travel', NULL, NULL, 0, 0, 'Why target: Regional kickoffs + dealer events. Vietnam signal: Likely. Partner angle: Emphasize quick access and strong hospitality network; offer structured programme templates.. Suggested route: Via DMC/agency', 'New', 'CORP', 'CIMB incentive Vietnam; CIMB offsite Da Nang', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-petronas-ma-2026', 'PETRONAS', 'Energy / Industrial', 'Malaysia', 'Da Nang', NULL, 'TBD', 'Corporate Affairs Events; HR Rewards; Travel Procurement', NULL, NULL, 0, 0, 'Why target: High frequency of corporate meetings/incentives. Vietnam signal: Likely. Partner angle: Offer executive-grade production, security, and privacy; propose leadership retreat formats and CSR.. Suggested route: Via agency', 'New', 'CORP', 'PETRONAS incentive Vietnam; PETRONAS conference Vietnam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-foxconn-hon-hai-ta-2026', 'Foxconn (Hon Hai)', 'Electronics / Manufacturing', 'Taiwan', 'Da Nang', NULL, 'TBD', 'Corporate HR; Rewards; Global Procurement; Supplier Management; Events', NULL, NULL, 0, 0, 'Why target: Large workforce; frequent incentives and supplier meetings. Vietnam signal: Likely Vietnam footprint. Partner angle: Pitch Vietnam as convenient for Taiwan teams; ACC for supplier conferences and internal kickoffs; offer bilingual support and robust production vendors.. Suggested route: Via Taiwan MICE agencies (ezTravel / iMICE) + direct', 'New', 'CORP', 'Foxconn Vietnam factory; Foxconn incentive Vietnam; Hon Hai Da Nang meeting', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-pegatron-ta-2026', 'Pegatron', 'Electronics / Manufacturing', 'Taiwan', 'Da Nang', NULL, 'TBD', 'Procurement; HR Rewards; Events', NULL, NULL, 0, 0, 'Why target: Supplier meetings and internal offsites. Vietnam signal: Likely Vietnam footprint. Partner angle: ACC for supplier summit + breakout workshops; package with resort stay.. Suggested route: Via agency + direct', 'New', 'CORP', 'Pegatron Vietnam factory; Pegatron offsite Vietnam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-compal-ta-2026', 'Compal', 'Electronics / Manufacturing', 'Taiwan', 'Da Nang', NULL, 'TBD', 'HR Rewards; Events; Procurement', NULL, NULL, 0, 0, 'Why target: Sales conferences. Vietnam signal: Likely. Partner angle: Offer predictable pricing and fast contracting; provide turnkey supplier summit format.. Suggested route: Via agency', 'New', 'CORP', 'Compal Vietnam factory; Compal incentive Vietnam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-celcomdigi-ma-2026', 'CelcomDigi', 'Telco', 'Malaysia', 'Da Nang', NULL, 'TBD', 'Marketing Events; HR Rewards; Travel', NULL, NULL, 0, 0, 'Why target: Sales conferences + partner events. Vietnam signal: Likely — verify. Partner angle: Offer 3–4 day incentive modules with strong evening programming; ACC for plenary and gala.. Suggested route: Via agency', 'New', 'CORP', 'CelcomDigi incentive Vietnam; CelcomDigi offsite Vietnam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-sime-darby-ma-2026', 'Sime Darby', 'Conglomerate / Industrial', 'Malaysia', 'Da Nang', NULL, 'TBD', 'Corporate Affairs; Events; Procurement', NULL, NULL, 0, 0, 'Why target: Dealer and leadership incentives. Vietnam signal: Likely — verify. Partner angle: ACC for dealer conference; highlight logistics and production readiness.. Suggested route: Via agency', 'New', 'CORP', 'Sime Darby incentive Vietnam; Sime Darby meeting Vietnam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('corp-sunway-group-ma-2026', 'Sunway Group', 'Real estate / Hospitality', 'Malaysia', 'Da Nang', NULL, 'TBD', 'HR; Events; Procurement', NULL, NULL, 0, 0, 'Why target: Corporate incentives and conferences. Vietnam signal: Likely — verify. Partner angle: ACC can host large team gatherings; propose family-friendly itinerary options.. Suggested route: Via agency', 'New', 'CORP', 'Sunway incentive Vietnam; Sunway group meeting Vietnam', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-vietnamdmccom-vi-2026', 'VietnamDMC.com', 'Vietnam DMC (Incentives)', 'Vietnam', 'Da Nang', 'https://vietnamdmc.com/vietnam-incentive/', 'TBD', 'CEO/Managing Director; Head of Incentives; Groups & MICE Sales; Product Manager (Central Vietnam)', NULL, NULL, 0, 0, 'Vietnam signal: Dedicated incentive travel positioning; sells Vietnam incentives. Partner angle: Offer ACC as the ''upgrade'' from hotel ballroom: bigger plenary, better staging, branding, and flow. Provide 2–3 sample Da Nang programs (3D2N/4D3N) with optional gala themes, CSR, team-building. Offer AV bundle + preferred supplier list.. Recommended action: Arrange familiarization visit; propose annual preferred agreement; co-create 3 packaged itineraries.', 'New', 'DMC', 'https://vietnamdmc.com/vietnam-incentive/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-bcd-meetings-events--si-2026', 'BCD Meetings & Events (Singapore)', 'Meetings & Events agency / TMC', 'Singapore', 'Da Nang', 'https://bcdme.com/en-sg/', 'TBD', 'Client Solutions Director; Program Manager; Venue Sourcing Lead; Strategic Meetings Mgmt', 'mervyn.tan@bcdme.com.my', NULL, 0, 0, 'Vietnam signal: Singapore HQ page + meetings/events services. Partner angle: Best for large corporates. ACC should position as ''value + scale'' vs Bangkok/Bali: modern venue, short-haul, beach incentive add-ons, and straightforward contracting. Offer a master venue brief + sample budgets for 200/500/800 pax.. Recommended action: Send venue brief + host virtual walkthrough; offer to support their venue sourcing with holding dates and quick quotes.. Contact: mervyn.tan@bcdme.com.my. Remark: MY Office', 'New', 'DMC', 'https://bcdme.com/en-sg/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-cwt-meetings-events--si-2026', 'CWT Meetings & Events (Singapore)', 'Meetings & Events agency', 'Singapore', 'Da Nang', 'https://www.cwt-meetings-events.com/talk-to-us/singapore/', 'TBD', 'Head of Client Development; Creative/Production Lead; Group Travel Lead', 'MayshanMZ@cwt-me.com', NULL, 0, 0, 'Vietnam signal: APAC centre of excellence in SG; strong event production capability. Partner angle: Pitch operational reliability: single venue for plenary/breakouts/expo; strong back-of-house for production; contingency plans. Offer a ''Da Nang playbook'' for event risk and logistics.. Recommended action: Send tech pack + rate ranges; propose a test RFP / pilot group.. Contact: MayshanMZ@cwt-me.com (Mayshan)
SufiH@cwt-me.com (Sufi)
Ochen@cwt-me.com (Ochen). Remark: SG Office', 'New', 'DMC', 'https://www.cwt-meetings-events.com/talk-to-us/singapore/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-fcm-travel-singapore-si-2026', 'FCM Travel (Singapore)', 'Corporate travel management (TMC) + MICE', 'Singapore', 'Da Nang', 'https://www.fcmtravel.com/en-fi/about-us/global-network/singapore', 'TBD', 'Regional Travel Manager; MICE/Groups Lead; Procurement Travel & Meetings', NULL, NULL, 0, 0, 'Vietnam signal: Corporate travel services include MICE; SG address listed. Partner angle: Approach via their group bookings/MICE team. ACC can offer preferred rates and ‘bundle’ packages for internal meetings and rewards trips. Provide duty-of-care and vendor compliance details.. Recommended action: Share venue brief + compliance info; ask for preferred supplier onboarding process.', 'New', 'DMC', 'https://www.fcmtravel.com/en-fi/about-us/global-network/singapore', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-apple-mice-apple-vac-ma-2026', 'Apple MICE (Apple Vacations)', 'Incentive / MICE agency', 'Malaysia', 'Da Nang', 'https://www.applevacations.my/en/mice.php', 'TBD', 'Head of Apple MICE; Incentive Travel Manager; Corporate Sales', 'enquiry@applevacations.my', NULL, 0, 0, 'Vietnam signal: Dedicated MICE page + MICE contact listed. Partner angle: Malaysia corporates do short-haul incentives; Da Nang is a fresh alternative to Bangkok/Bali. ACC should offer packaged pricing and fast turnaround, and suggest offsite dinners + CSR activities in Hoi An/Da Nang.. Recommended action: Email intro + propose 2 sample programmes; invite top planner for inspection.. Contact: enquiry@applevacations.my (Vanness Lai). Remark: MY Office', 'New', 'DMC', 'https://www.applevacations.my/en/mice.php', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-golden-destinations--ma-2026', 'Golden Destinations (GD MICE)', 'MICE travel wholesaler / B2B', 'Malaysia', 'Da Nang', 'https://www.goldendestinations.com/mice', 'TBD', 'GD MICE Director; Key Account; Group Incentives Manager', 'feedback@gd.my', NULL, 0, 0, 'Vietnam signal: GD MICE positioned for custom-made travel solutions. Partner angle: Work them as a B2B distribution partner. Provide ACC-ready collateral: photos, floorplans, capacity, menus, and sample budgets. Offer a fixed ‘MICE bundle’ they can plug into proposals.. Recommended action: Partner meeting; provide packaged offers and marketing collateral.. Contact: feedback@gd.my (Sunny Ong). Remark: MY Office', 'New', 'DMC', 'https://www.goldendestinations.com/mice', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-mayflower-malaysia-ma-2026', 'Mayflower (Malaysia)', 'Corporate travel + MICE', 'Malaysia', 'Da Nang', 'https://www.mayflower.com.my/contactus', 'TBD', 'MICE Planner; Corporate Accounts; Travel Procurement Lead', NULL, NULL, 0, 0, 'Vietnam signal: Large corporate travel group with MICE capability. Partner angle: Pitch annual corporate calendars: kickoffs, awards nights, dealer incentives. ACC can offer yearly preferred agreements and rate protection. Provide risk and safety plan plus vendor list.. Recommended action: Intro + share venue brief + propose preferred agreement.', 'New', 'DMC', 'https://mayflower-group.com/images/stories/PDF/corporateprofile.pdf', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-eztravel-易遊網-mice-ta-2026', 'ezTravel 易遊網 (MICE)', 'Outbound corporate/MICE travel', 'Taiwan', 'Da Nang', 'https://vacation.eztravel.com.tw/pkgfrn/miceForm', 'TBD', 'MICE Product Manager; Corporate Sales; Group Travel Lead', NULL, NULL, 0, 0, 'Vietnam signal: Dedicated MICE form with MICE email/phone. Partner angle: Provide Chinese-language ACC kit. Emphasize Taiwan–Da Nang nonstop connectivity and ease: short flight, resort + meeting in one. Offer packaged programmes and quick quote SLAs.. Recommended action: Send Chinese kit + invite key MICE product owner for virtual walkthrough; propose joint promotion.', 'New', 'DMC', 'https://vacation.eztravel.com.tw/pkgfrn/miceForm', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-flying-tour-imice-ka-ta-2026', 'Flying Tour / iMICE (Kaohsiung)', 'Outbound MICE organiser / DMC', 'Taiwan', 'Da Nang', 'https://www.fly168.com.tw/inb/', 'TBD', 'iMICE BD Manager; Project Director; Corporate Sales', NULL, NULL, 0, 0, 'Vietnam signal: Subsidiary iMICE focuses on MICE planning; corporate clients. Partner angle: Position Da Nang as short-haul incentive option from Taiwan. Offer venue assurance and production support; connect them with local Da Nang DMCs for ground ops.. Recommended action: Intro + propose 1 pilot group; provide Chinese collateral + sample budgets.', 'New', 'DMC', 'https://www.fly168.com.tw/inb/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-ctm-taiwan-ta-2026', 'CTM (Taiwan)', 'Corporate travel management / TMC', 'Taiwan', 'Da Nang', 'https://asia.travelctm.com/contact/', 'TBD', 'Travel Manager; Meetings & Events lead; Procurement', NULL, NULL, 0, 0, 'Vietnam signal: CTM has Taiwan office listed on Asia contact page. Partner angle: Use CTM as channel to corporates with managed travel. ACC can be a preferred venue and provide quick RFP responses.. Recommended action: Contact Taiwan office; ask about meetings/events referrals and preferred venue onboarding.', 'New', 'DMC', 'https://asia.travelctm.com/contact/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-ctm-singapore-si-2026', 'CTM (Singapore)', 'Corporate Travel Management (CTM)', 'Singapore / Regional', 'Da Nang', 'https://asia.travelctm.com/contact/', 'TBD', 'Travel Manager; Meetings & Events Lead; Procurement (Travel & Meetings)', NULL, NULL, 0, 0, 'Vietnam signal: Major TMC with SG office; can connect to meetings/events division. Partner angle: Use CTM to reach corporates with managed travel programs. Provide ACC as preferred venue and offer fast quotes + clear cancellation/attrition terms.. Recommended action: Intro + request to be added to preferred venues list; share rate ranges and venue tech pack.', 'New', 'DMC', 'https://asia.travelctm.com/contact/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-1-mice-singapore-si-2026', '1 M.I.C.E. (Singapore)', 'Local corporate event organiser', 'Singapore', 'Da Nang', 'https://1mice.com.sg/contact/', 'TBD', 'Managing Partner; Business Development; Client Servicing Manager', NULL, NULL, 0, 0, 'Vietnam signal: Corporate event organiser; can run incentives/meetings and may need destination partners. Partner angle: Treat as an organiser needing destination product. ACC can provide a ‘Da Nang event blueprint’ + connect them with VN DMC partners for ground. Offer co-selling and introductions.. Recommended action: Intro + propose partnership + introductions to 2–3 Vietnam DMCs.', 'New', 'DMC', 'https://1mice.com.sg/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-ovation-global-dmc-s-si-2026', 'Ovation Global DMC (Singapore)', 'Destination Management Company (Global)', 'Singapore', 'Da Nang', 'https://ovationdmc.com/destinations/singapore/', 'TBD', 'Director Corporate; Business Development; Event Solutions Manager', NULL, NULL, 0, 0, 'Vietnam signal: Singapore DMC office page + global scale. Partner angle: Use Ovation as a global DMC channel for corporates and agencies. ACC angle: Da Nang as ''fresh'' incentive destination with strong venue capability. Offer a standard Da Nang MICE package (venue + hotels + experiences) they can sell globally.. Recommended action: Intro + request preferred partner status for Da Nang; share standard package + rates.', 'New', 'DMC', 'https://ovationdmc.com/destinations/singapore/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-prime-travel-singapo-si-2026', 'Prime Travel (Singapore)', 'Corporate travel + MICE', 'Singapore', 'Da Nang', 'https://www.primetravel.com.sg/mice.html', 'TBD', 'MICE Specialists; Corporate Sales; Incentive Travel Manager', NULL, NULL, 0, 0, 'Vietnam signal: Has MICE specialists and dedicated MICE page. Partner angle: Pitch as corporate travel agency that can route groups into Vietnam. ACC should provide fast quote SLAs and packaged programmes; propose joint marketing to their corporate base.. Recommended action: Intro + send packages + suggest a pilot corporate group.', 'New', 'DMC', 'https://www.primetravel.com.sg/mice.html', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('dmc-holiday-tours-travel-ma-2026', 'Holiday Tours & Travel (Malaysia)', 'Corporate travel + MICE', 'Malaysia', 'Da Nang', 'https://www.holidaytours.com.my/', 'TBD', 'Head of MICE; Corporate Accounts; Business Travel Manager', NULL, NULL, 0, 0, 'Vietnam signal: Promotes comprehensive MICE solutions. Partner angle: Approach as corporate travel manager. Offer ready-to-sell proposals (3D2N/4D3N) and highlight direct flights + high value. Provide a ‘venue comparison’ vs hotel ballrooms.. Recommended action: Intro + send packaged proposals; invite them to a joint FAM trip with VN DMC partner.', 'New', 'DMC', 'https://www.holidaytours.com.my/', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Total: 27 leads (12 CORP, 15 DMC)