-- Import script for Normal leads from Normal.csv
-- Generated: 2026-02-13 17:43:51
-- Usage: Run this script after running migrations 003 and 004

-- Found 17 Normal leads (type = NULL)

INSERT INTO leads (
    id, company_name, industry, country, city, website,
    key_person_name, key_person_title, key_person_email, key_person_phone, key_person_linkedin,
    total_events, vietnam_events, notes, status, last_contacted,
    past_events_history, research_notes, secondary_person_name, secondary_person_title,
    secondary_person_email, number_of_delegates, lead_score, last_score_update, type,
    created_at, updated_at
) VALUES
    ('normal-asiapacific-symposium-on-electromagnetic', 'Asia‑Pacific Symposium on Electromagnetic Compatibility (APEMC)', 'Physics / Electromagnetics', 'International', 'Da Nang', 'http://www.ewh.ieee.org/ieee/apo/', 'Ms Ewell Tan', NULL, 'ewell.tan@ieee.org', '+65 6778 2873', NULL, 0, 0, 'Breakout rooms: 3–5. Cycle: Annual • May. Suggested VN Host: IEEE Vietnam Section; University of Danang. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 700, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-asiapacific-interventional-oncology-conf', 'Asia‑Pacific Interventional Oncology Conference (APCIO)', 'Medical / Oncology', 'International', 'Da Nang', NULL, 'Dr Alex Tang', NULL, 'secretariat@mysir.org', NULL, NULL, 0, 0, 'Breakout rooms: 3–5. Cycle: Biennial. Suggested VN Host: Vietnam Society of Interventional Radiology (VSIR); Vinmec. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 1000, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-annual-meeting-of-the-asian-organization', 'Annual Meeting of the Asian Organization for Crohn’s & Colitis (AOCC)', 'Medical / Gastroenterology', 'Malaysia', 'Da Nang', 'https://aocc-ibd.org', 'Dr Tan Soek Siam', NULL, 'tanss@selayanghospital.gov.my', NULL, NULL, 0, 0, 'Breakout rooms: 3–5. Cycle: Annual • June. Suggested VN Host: Vietnam Association of Gastroenterology; Bach Mai Hospital. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 900, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-society-of-wood-science-technology-swst-', 'Society of Wood Science & Technology (SWST) Convention', 'Forest products', 'International', 'Da Nang', 'http://www.swst.org', 'Mrs Vicki L. Herian', NULL, 'vicki@swst.org', '+1 608 577 1342', NULL, 0, 0, 'Breakout rooms: 2–3. Cycle: Annual. Suggested VN Host: VIFORES; Vietnam National University of Forestry. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 280, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-aapa-aviation-emergency-response-confere', 'AAPA Aviation Emergency Response Conference', 'Aviation / Safety', 'Malaysia', 'Da Nang', 'http://www.aapairlines.org', 'AAPA Secretariat', NULL, 'info@aapa.org.my', '+60 3 2162 1888', NULL, 0, 0, 'Breakout rooms: Plenary only. Cycle: Biennial. Suggested VN Host: Vietnam Airlines; Civil Aviation Authority of Vietnam. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 134, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-asiapacific-council-of-optometry-apco', 'Asia‑Pacific Council of Optometry (APCO)', 'Medical / Optometry', 'Asia-Pacific', 'Da Nang', 'http://www.asiapacificoptometry.org', 'APCO Secretariat', NULL, 'secretariat@asiapacificoptometry.org', '+61 7 3138 5738', NULL, 0, 0, 'Breakout rooms: 3–4. Cycle: Biennial. Suggested VN Host: Vietnam Optometry Association; Hanoi Medical University. Royalty/Licence: Unknown', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 500, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-international-association-of-gerontology', 'International Association of Gerontology & Geriatrics (IAGG Asia)', 'Healthy ageing', 'International', 'Da Nang', 'https://www.iagg.net', 'IAGG Secretariat', NULL, 'MSPH-IAGG@cumc.columbia.edu', NULL, NULL, 0, 0, 'Breakout rooms: 4–6. Cycle: Quadrennial. Suggested VN Host: Vietnam Geriatrics Association; National Geriatric Hospital. Royalty/Licence: TBC', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 1000, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-christian-conference-of-asia-cca-assembl', 'Christian Conference of Asia (CCA) Assembly', 'Religious / Social', 'Hong Kong', 'Da Nang', 'http://www.cca.org.hk', 'CCA Secretariat', NULL, 'cca@cca.org.hk', NULL, NULL, 0, 0, 'Breakout rooms: 3–4. Cycle: 4‑yearly. Suggested VN Host: Vietnam Evangelical Alliance; Faith‑based NGOs. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 800, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-asian-society-of-transplantation-ast-con', 'Asian Society of Transplantation (AST) Congress', 'Medical / Transplant', 'International', 'Da Nang', 'http://www.txasia.org', 'AST Secretariat', NULL, 'info@siut.org', NULL, NULL, 0, 0, 'Breakout rooms: 4–6. Cycle: Biennial. Suggested VN Host: Vietnam Transplant Association; Viet Duc Hospital. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 1000, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-asiaoceania-thyroid-association-aota-con', 'Asia‑Oceania Thyroid Association (AOTA) Congress', 'Medical / Endocrinology', 'International', 'Da Nang', NULL, 'AOTA Secretariat', NULL, 'aota_office@aota.org', NULL, NULL, 0, 0, 'Breakout rooms: 2–4. Cycle: Biennial. Suggested VN Host: Vietnam Endocrinology Society; National Hospital of Endocrinology. Royalty/Licence: Unknown', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 800, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-federation-of-asiapacific-retailers-asso', 'Federation of Asia‑Pacific Retailers Association (FAPRA) Congress', 'Retail trade', 'International', 'Da Nang', 'http://www.fapra.net', 'FAPRA Secretariat', NULL, 'cgcc_intl@aliyun.com', NULL, NULL, 0, 0, 'Breakout rooms: 4–6. Cycle: Annual. Suggested VN Host: Vietnam Retailers Association; Saigon Co.op. Royalty/Licence: Revenue share likely', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 1000, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-international-water-association-iwa-asia', 'International Water Association (IWA) Asia‑Pacific Regional Conference', 'Water & sanitation', 'International', 'Da Nang', 'https://www.iwa-network.org', 'Mr Ganesh Pangare', NULL, 'ganesh.pangare@iwahq.org', NULL, NULL, 0, 0, 'Breakout rooms: 4–5. Cycle: Biennial. Suggested VN Host: Vietnam Water Supply & Sewerage Association; Danang Water Co.. Royalty/Licence: Unknown', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 800, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-world-wide-web-conference-iw3c2', 'World Wide Web Conference (IW3C2)', 'ICT / Internet', 'International', 'Da Nang', NULL, 'IW3C2 Secretariat', NULL, 'info@iw3c2.org', NULL, NULL, 0, 0, 'Breakout rooms: 6–8. Cycle: Annual • April. Suggested VN Host: Vietnam Internet Association; Posts & Telecom Institute. Royalty/Licence: Hosting fee / royalty', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 1200, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-international-vegetarian-union-ivu-world', 'International Vegetarian Union (IVU) World Congress', 'Lifestyle / Food', 'International', 'Da Nang', 'https://www.ivu.org', 'IVU Secretariat', NULL, 'info@ivu.org', NULL, NULL, 0, 0, 'Breakout rooms: 3–5. Cycle: Triennial. Suggested VN Host: Vietnam Vegetarian Society; Trúc Lâm Monastery Network. Royalty/Licence: None stated', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 600, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-international-fertilizer-association-ifa', 'International Fertilizer Association (IFA) Global Conference', 'Agriculture', 'International', 'Da Nang', 'https://www.fertilizer.org', 'IFA Secretariat', NULL, 'info@fertilizer.org', NULL, NULL, 0, 0, 'Breakout rooms: 4–6. Cycle: Annual. Suggested VN Host: Vietnam Fertilizer Association; PVFCCo. Royalty/Licence: Licence fee', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 900, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-international-council-for-open-distance-', 'International Council for Open & Distance Education (ICDE) World Conference', 'Higher‑ed Tech', 'International', 'Da Nang', 'https://www.icde.org', 'ICDE Secretariat', NULL, 'icde@icde.org', NULL, NULL, 0, 0, 'Breakout rooms: 5–7. Cycle: Biennial. Suggested VN Host: Hanoi Open University; Ministry of Education & Training. Royalty/Licence: Licence / revenue share', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 1200, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('normal-international-menopause-society-ims-cong', 'International Menopause Society (IMS) Congress', 'Women’s Health', 'International', 'Da Nang', 'https://www.imsociety.org', 'IMS Office', NULL, 'ims.society@imsociety.org', NULL, NULL, 0, 0, 'Breakout rooms: 4–6. Cycle: Biennial. Suggested VN Host: Vietnam Menopause Society; National Obstetrics & Gynecology Hospital. Royalty/Licence: TBC', 'New', NULL, NULL, NULL, NULL, NULL, NULL, 1200, NULL, NULL, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

-- Total: 17 normal leads (type = NULL)